version: "3.8"

services:
  app:
    build: .
    ports:
      - "8888:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/blog_api
      - JWT_SECRET=your_jwt_secret_here
      - UPLOAD_DIR=./uploads
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
